name: Build and Publish to PyPI

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: 
      name: publish
    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --no-dev

    - name: Build and publish to PyPI
      run: |
        uv build
        uv publish --token ${{ secrets.PYPI_TOKEN }}
