name: Build and Publish Docker Image

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: 
      name: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          import toml
          with open('pyproject.toml', 'r') as f:
              data = toml.load(f)
          version = data['project']['version']
          print(f"::set-output name=version::{version}")
        shell: python

      - name: Show version
        run: |
          echo "Version: ${{ steps.get_version.outputs.version }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            twosix26/alist-mikananirss:v${{ steps.get_version.outputs.version }}
            twosix26/alist-mikananirss:latest
